fix: ensure report rustc version in more cases (skip ci)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -89,6 +89,8 @@ check_bin_lib() {
     echo "The library was not found at <${LIBR_GLAREDB_PATH}>,"
     echo "but was found at <${LIBR_GLAREDB_DEFAULT_PATH}>."
     echo "No need to build it."
+    echo ""
+    echo "Note: rustc version: $(rustc -V || echo 'Not found')"
     echo "--------------------------------------------------------------------"
     echo ""
     sed -e "s|@TARGET@||" src/Makevars.in >src/Makevars
